name: Build BPB Worker

on:
  push:
    branches:
      - main
  schedule:
        # Runs everyday at 1:00 AM
        - cron: "0 1 * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "latest"

      - name: Clone BPB project
        run: |
          cd worker/bpb
          git clone https://github.com/bia-pain-bache/BPB-Worker-Panel.git
          cd BPB-Worker-Panel

      - name: Install dependencies
        run: |
          cd worker/bpb/BPB-Worker-Panel
          npm install

      - name: Build project
        run: |
          cd worker/bpb/BPB-Worker-Panel
          npx wrangler deploy src/worker.js --name bpb-worker-panel --compatibility-flag [nodejs_compat] --compatibility-date 2024-10-26 --dry-run --outdir=dist
          cp -f dist/worker.js ../origin.js
          cd ..
          rm -rf BPB-Worker-Panel
      
      - name: Obfuscate BPB worker js
        run: |
          npm install -g javascript-obfuscator
          javascript-obfuscator worker/bpb/origin.js --output worker/bpb/_worker.js \
          --compact true \
          --control-flow-flattening true \
          --control-flow-flattening-threshold 1 \
          --dead-code-injection true \
          --dead-code-injection-threshold 1 \
          --identifier-names-generator hexadecimal \
          --rename-globals true \
          --string-array true \
          --string-array-encoding 'rc4' \
          --string-array-threshold 1 \
          --transform-object-keys true \
          --unicode-escape-sequence true

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: main
          commit_message: ':arrow_up: update latest bpb worker'
          commit_author: 'github-actions[bot] <github-actions[bot]@users.noreply.github.com>'
          push_options: '--set-upstream'
